FROM ubuntu:16.04

COPY . /
WORKDIR /

RUN apt update \
  && apt-get install -y python3-pip python3-dev \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python

RUN pip3 install -r requirements.txt

RUN pip3 install flask-restful

RUN pip3 install  requests

ARG id

ENV id=${id}

CMD python3 Order.py ${id}