FROM ubuntu:16.04

WORKDIR /lab3

ADD Frontend.py /lab3
ADD requirements.txt /lab3
ADD inventory.sql /lab3
ADD utils.py /lab3
ADD server_config /lab3

RUN apt update && apt-get install -y python3-pip python3-dev \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python

RUN pip3 install -r requirements.txt

RUN pip3 install  requests

